/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_SCACV;

/**
 *
 * @author Marina
 */
public class BotonesRecambio extends javax.swing.JPanel {

    public boolean hayQueRepostar = false;
    public boolean hayQuePastillas = false;
    public boolean hayQueRevisar = false;
    public boolean hayQueAceite = false;
    
    public BotonesRecambio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRepostar = new javax.swing.JButton();
        botonPastillas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonRevision = new javax.swing.JButton();
        botonAceite = new javax.swing.JButton();

        setBackground(new java.awt.Color(41, 62, 69));
        setPreferredSize(new java.awt.Dimension(330, 170));

        botonRepostar.setBackground(new java.awt.Color(193, 124, 116));
        botonRepostar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        botonRepostar.setForeground(new java.awt.Color(41, 62, 69));
        botonRepostar.setText("REPOSTAR");
        botonRepostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRepostarActionPerformed(evt);
            }
        });

        botonPastillas.setBackground(new java.awt.Color(193, 124, 116));
        botonPastillas.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        botonPastillas.setForeground(new java.awt.Color(41, 62, 69));
        botonPastillas.setText("<html>CAMBIAR <br/>PASTILLAS</html>");
        botonPastillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPastillasActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gasStation.png"))); // NOI18N

        botonRevision.setBackground(new java.awt.Color(193, 124, 116));
        botonRevision.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        botonRevision.setForeground(new java.awt.Color(41, 62, 69));
        botonRevision.setText("<html>REVISIÓN <br/>GENERAL</html>");
        botonRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRevisionActionPerformed(evt);
            }
        });

        botonAceite.setBackground(new java.awt.Color(193, 124, 116));
        botonAceite.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        botonAceite.setForeground(new java.awt.Color(41, 62, 69));
        botonAceite.setText("<html>CAMBIAR <br/>ACEITE</html>");
        botonAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(botonRepostar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonPastillas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAceite, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRepostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(botonPastillas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceite, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRepostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRepostarActionPerformed
        hayQueRepostar = true;
    }//GEN-LAST:event_botonRepostarActionPerformed

    private void botonPastillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPastillasActionPerformed
        hayQuePastillas = true;
    }//GEN-LAST:event_botonPastillasActionPerformed

    private void botonRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevisionActionPerformed
        hayQueRevisar = true;
    }//GEN-LAST:event_botonRevisionActionPerformed

    private void botonAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceiteActionPerformed
        hayQueAceite = true;
    }//GEN-LAST:event_botonAceiteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceite;
    private javax.swing.JButton botonPastillas;
    private javax.swing.JButton botonRepostar;
    private javax.swing.JButton botonRevision;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
